// 3-3-Svelte/src/components/personTable.svelte

	<div class="grid-component">
		<div class="form-container">
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Age</th>
			</tr>
            {#each information as row, index}
            <tr>
				<td>{row.firstName}</td>
				<td>{row.lastName}</td>
				<td>{row.age}</td>
				<td>
					<button on:click={()=>deleteEntry(index)}>x</button>
                </td>
            </tr>
            {/each}
		</div>
	</div>


<script>

   function	deleteEntry(index) {
			information.splice(index, 1);
            information = information;
		}

 export let information = {
      type: Array,
      required: true
    }


</script>


<style>
	.grid-component {
		flex: 1 1 30%; margin: 5px; 
		padding: 2rem;
  }
button {
		border: none;
	}
	table, th, td {
		border: 0.1rem solid black;
		margin: auto 0;
		text-align: center;
	}
</style>

// 3x3/src/components/personTable.vue
<template>
	<div class="grid-component">
		<div class="form-container">
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Age</th>
			</tr>
            <tr v-for="(row, index) in information" :key="index">
				<td>{{ row["firstName"] }}</td>
				<td>{{ row["lastName"] }}</td>
				<td>{{ row["age"] }}</td>
				<td>
					<button v-on:click="deleteEntry(index)">x</button>
				</td>
			</tr>
		</div>
	</div>
</template>

<script>
export default {
	methods: {
		deleteEntry(index) {
			this.$emit('delete', index)
		}
	},
	props: {
        information: {
            type: Array,
            required: true
        },
	}
}
</script>

<style>
.form-container {
	display: inline;
}
</style>
